cache:
  key: "${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}"
  paths:
    - ~/.composer # cache the composer directory

# set the default docker image
image: registry.gitlab.com/tjvb/phpimages:php80

stages:
  - prepare
  - check
  - test
  - report

prepare_cache:
  stage: prepare
  script:
    - composer install
  cache:
    key: "${CI_PROJECT_NAME}"
    # we use the with this job to create an artifact with the composer parts and use the cache to speed it up
    policy: pull-push
    paths:
      - vendor/
  # we use this artifact for all the jobs
  artifacts:
    name: "vendor"
    paths:
      - vendor/*
    expire_in: 2 hour

validate:
  stage: check
  script:
    - composer validate
    - vendor/bin/phpcs --basepath=. --report-json=php_codesniffer.json
  artifacts:
    paths:
      - php_codesniffer.json
    when: always
  needs:
    - prepare_cache
  dependencies:
    - prepare_cache

phpmd:
  image: phpqa/phpmd
  stage: check
  script:
    - phpmd src/ text phpmd.xml.dist
  needs: []
  dependencies: []

psalm:
  stage: check
  script:
    # check for psalm errors
    - vendor/bin/psalm --report=psalm.json
  artifacts:
    paths:
      - psalm.json
    when: always
  needs:
    - prepare_cache
  dependencies:
    - prepare_cache

# PHP 8.0
test:8.0_lowest:
  image: registry.gitlab.com/tjvb/phpimages:php80
  stage: test
  script:
    - composer update --prefer-lowest
    - vendor/bin/phpunit --coverage-text --colors=never --coverage-cobertura=phpunitresult/cobertura-coverage.xml --log-junit=phpunitresult/junit.xml
    - sed -i 's~ filename="~ filename="src/~' phpunitresult/cobertura-coverage.xml
  artifacts:
    reports:
      junit: phpunitresult/junit.xml
      cobertura: phpunitresult/cobertura-coverage.xml
  needs:
    - prepare_cache
  dependencies:
    - prepare_cache

test:8.0_laravel9:
  image: registry.gitlab.com/tjvb/phpimages:php80
  stage: test
  script:
    - composer require --dev "orchestra/testbench=^7" phpunit/phpunit=^9.0
    - vendor/bin/phpunit --coverage-text --colors=never --coverage-cobertura=phpunitresult/cobertura-coverage.xml --log-junit=phpunitresult/junit.xml
    - sed -i 's~ filename="~ filename="src/~' phpunitresult/cobertura-coverage.xml
  artifacts:
    reports:
      junit: phpunitresult/junit.xml
      cobertura: phpunitresult/cobertura-coverage.xml
  needs:
    - prepare_cache
  dependencies:
    - prepare_cache

# PHP 8.1
test:8.1_lowest:
  image: registry.gitlab.com/tjvb/phpimages:php81
  stage: test
  script:
    - composer update --prefer-lowest
    - vendor/bin/phpunit --coverage-text --colors=never --coverage-cobertura=phpunitresult/cobertura-coverage.xml --log-junit=phpunitresult/junit.xml
    - sed -i 's~ filename="~ filename="src/~' phpunitresult/cobertura-coverage.xml
  artifacts:
    reports:
      junit: phpunitresult/junit.xml
      cobertura: phpunitresult/cobertura-coverage.xml
  needs:
    - prepare_cache
  dependencies:
    - prepare_cache

test:8.1_laravel9:
  image: registry.gitlab.com/tjvb/phpimages:php81
  stage: test
  script:
    - composer require --dev "orchestra/testbench=^7" phpunit/phpunit=^9.0
    - vendor/bin/phpunit --coverage-text --colors=never --coverage-cobertura=phpunitresult/cobertura-coverage.xml --log-junit=phpunitresult/junit.xml
    - sed -i 's~ filename="~ filename="src/~' phpunitresult/cobertura-coverage.xml
  artifacts:
    reports:
      junit: phpunitresult/junit.xml
      cobertura: phpunitresult/cobertura-coverage.xml
  needs:
    - prepare_cache
  dependencies:
    - prepare_cache

CodeQuality:
  stage: report
  needs:
      - prepare_cache
      - psalm
      - validate
  dependencies:
    - prepare_cache
    - psalm
    - validate
  script:
    - composer require --dev beechit/json-to-code-climate-subset-converter:^1.4
    - vendor/bin/converter convert --psalm --php_codesniffer
  artifacts:
    reports:
      codequality: code-climate.json
    when: always
