# Composer stores all downloaded packages in the vendor/ directory.
# Do not use the following if the vendor/ directory is commited to
# your git repository.
cache:
  paths:
  - vendor/

before_script:
# Install git, the php image doesn't have installed
- apt-get update -yqq
- apt-get install git -yqq

# Install composer
- curl -sS https://getcomposer.org/installer | php
# Install Xdebug
- pecl install xdebug
# Enable Xdebug
- docker-php-ext-enable xdebug

test:
  image: php:7.0
  script:
  - php composer.phar -q validate
  - php composer.phar -q install
  - vendor/bin/phpcs --standard=PSR2 src/
  - vendor/bin/phpmd src/ text codesize,naming,design,unusedcode

# We test PHP7.0
test:7.0:
  image: php:7.0
  script:
  - php composer.phar -q install
  - vendor/bin/phpunit --configuration phpunit.xml --coverage-text --colors=never

# We test PHP7.1
test:7.1:
  image: php:7.1
  script:
  - php composer.phar -q install
  - vendor/bin/phpunit --configuration phpunit.xml --coverage-text --colors=never

# We test PHP7.2
test:7.2:
  image: php:7.2
  script:
  - php composer.phar -q install
  - vendor/bin/phpunit --configuration phpunit.xml --coverage-text --colors=never

# We will test the different Laravel versions
test:7.0_laravel5.0:
  image: php:7.0
  script:
  - php composer.phar -q remove --dev orchestra/testbench
  - php composer.phar -q require --dev "orchestra/testbench=~3.0"
  - vendor/bin/phpunit --configuration phpunit.xml --coverage-text --colors=never

test:7.0_laravel5.1:
  image: php:7.0
  script:
  - php composer.phar -q remove --dev orchestra/testbench
  - php composer.phar -q require --dev "orchestra/testbench=~3.1"
  - vendor/bin/phpunit --configuration phpunit.xml --coverage-text --colors=never

test:7.0_laravel5.2:
  image: php:7.0
  script:
  - php composer.phar -q remove --dev orchestra/testbench
  - php composer.phar -q require --dev "orchestra/testbench=~3.2"
  - vendor/bin/phpunit --configuration phpunit.xml --coverage-text --colors=never

test:7.0_laravel5.3:
  image: php:7.0
  script:
  - php composer.phar -q remove --dev orchestra/testbench
  - php composer.phar -q require --dev "orchestra/testbench=~3.3"
  - vendor/bin/phpunit --configuration phpunit.xml --coverage-text --colors=never

test:7.0_laravel5.4:
  image: php:7.0
  script:
  - php composer.phar -q remove --dev orchestra/testbench
  - php composer.phar -q require --dev "orchestra/testbench=~3.4"
  - vendor/bin/phpunit --configuration phpunit.xml --coverage-text --colors=never

test:7.1_laravel5.6:
  image: php:7.1
  script:
  - php composer.phar -q remove --dev orchestra/testbench
  - php composer.phar -q require --dev "orchestra/testbench=~3.6"
  - vendor/bin/phpunit --configuration phpunit.xml --coverage-text --colors=never
