cache:
  key: "%CI_COMMIT_REF_SLUG%"
  paths:
  - ~/.composer # cache the composer directory

# set the default docker image
image: php:7.2

stages:
  - check
  - test

before_script:
# Install git, the php image doesn't have installed
- apt-get update -yqq
- apt-get install git -yqq

# Install composer
- curl -sS https://getcomposer.org/installer | php
# Install Xdebug
- pecl install xdebug
# Enable Xdebug
- docker-php-ext-enable xdebug

validate:
  stage: check
  script:
  - php composer.phar validate
  - php composer.phar install
  - vendor/bin/phpcs --standard=PSR2 src/

# We run phpmd in a seperated job that use the phar file
phpmd:
  stage: check
  script:
  - curl -OL http://static.phpmd.org/php/latest/phpmd.phar
  - php phpmd.phar src/ text codesize,naming,design,unusedcode

# We test PHP7.2
test:7.2:
  stage: test
  script:
  - php composer.phar install
  - vendor/bin/phpunit --coverage-text --colors=never


test:7.2_lowest:
  stage: test
  script:
    - php composer.phar update --prefer-lowest
    - vendor/bin/phpunit --coverage-text --colors=never
    -
test:7.2_laravel5.7:
  stage: test
  script:
  - php composer.phar require --dev "orchestra/testbench=~3.7" phpunit/phpunit=~7.0
  - vendor/bin/phpunit --coverage-text --colors=never

test:7.2_laravel5.8:
  stage: test
  script:
  - php composer.phar require --dev "orchestra/testbench=~3.8" phpunit/phpunit=~8.0
  - vendor/bin/phpunit --coverage-text --colors=never
