cache:
  key: "${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}"
  paths:
    - ~/.composer # cache the composer directory

# set the default docker image
image: registry.gitlab.com/tjvb/phpimages:php80

stages:
  - prepare
  - check
  - test
  - report

prepare_cache:
  stage: prepare
  script:
    - composer validate
    - composer install
  cache:
    key: "${CI_PROJECT_NAME}"
    # we use the with this job to create an artifact with the composer parts and use the cache to speed it up
    policy: pull-push
    paths:
      - vendor/
  # we use this artifact for all the jobs
  artifacts:
    name: "vendor"
    paths:
      - vendor/*
    expire_in: 2 hour

lint:
  stage: check
  script:
    # lint recursive
    - find src/ -type f -name '*.php' -exec php -l {} \; | (! grep -v "No syntax errors detected" )
  dependencies: []

phpstan:
  stage: check
  script:
    # check for phpstan errors
    - php -d memory_limit=500M vendor/bin/phpstan analyse --error-format=gitlab | tee phpstan.json
    - cat phpstan.json
  dependencies:
    - prepare_cache
  needs:
    - prepare_cache
  artifacts:
    paths:
      - phpstan.json
    reports:
      codequality: phpstan.json
    when: always

phpmd:
  stage: check
  script:
    - composer phpmd
  needs:
    - prepare_cache
  dependencies:
    - prepare_cache

code-style:
  stage: check
  script:
    - vendor/bin/ecs
  dependencies:
    - prepare_cache
  needs:
    - prepare_cache

# We check the content with vale
vale:
  image:
    name: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/jdkato/vale
    entrypoint: [""]
  stage: check
  script:
    - /bin/vale --config=tools/vale/.vale.ini README.md
  needs: []
  dependencies: []

infection:
  image: registry.gitlab.com/tjvb/phpimages:php83
  stage: test
  script:
    - composer install
    - vendor/bin/phpunit --migrate-configuration
    - vendor/bin/infection
  dependencies:
    - prepare_cache
  needs:
    - prepare_cache
  artifacts:
    paths:
      - build/infection/
    reports:
      codequality: build/infection/code-climate-gitlab.json
    when: always


test_lowest:
  parallel:
  image: registry.gitlab.com/tjvb/phpimages:php80
  stage: test
  script:
    - composer update --prefer-lowest
    - vendor/bin/phpunit --coverage-text --colors=never --coverage-cobertura=phpunitresult/cobertura-coverage.xml --log-junit=phpunitresult/junit.xml
    - sed -i 's~ filename="~ filename="src/~' phpunitresult/cobertura-coverage.xml
  coverage: '/^\s*Lines:\s*\d+.\d+\%/'
  artifacts:
    reports:
      junit: phpunitresult/junit.xml
      coverage_report:
        coverage_format: cobertura
        path: phpunitresult/cobertura-coverage.xml
  needs:
    - prepare_cache
  dependencies:
    - prepare_cache

test:
  parallel:
    matrix:
      - LARAVEL: 9
        TESTBENCH: 7
        PHP:
          - 80
          - 81
          - 82
          - 83
      - LARAVEL: 10
        TESTBENCH: 8
        PHP:
          - 81
          - 82
          - 83
      - LARAVEL: 11
        TESTBENCH: 9
        PHP:
          - 82
          - 83
  image: registry.gitlab.com/tjvb/phpimages:php$PHP
  stage: test
  script:
    - echo "Laravel $LARAVEL"
    - composer require --dev "orchestra/testbench=^$TESTBENCH"
    - vendor/bin/phpunit --coverage-text --colors=never --coverage-cobertura=phpunitresult/cobertura-coverage.xml --log-junit=phpunitresult/junit.xml
    - sed -i 's~ filename="~ filename="src/~' phpunitresult/cobertura-coverage.xml
  coverage: '/^\s*Lines:\s*\d+.\d+\%/'
  artifacts:
    reports:
      junit: phpunitresult/junit.xml
      coverage_report:
        coverage_format: cobertura
        path: phpunitresult/cobertura-coverage.xml
  needs:
    - prepare_cache
  dependencies:
    - prepare_cache
