cache:
  key: "${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}"
  paths:
    - ~/.composer # cache the composer directory

# set the default docker image
image: registry.gitlab.com/tjvb/phpimages:php80

stages:
  - prepare
  - check
  - test
  - report

prepare_cache:
  stage: prepare
  script:
    - composer install
  cache:
    key: "${CI_PROJECT_NAME}"
    # we use the with this job to create an artifact with the composer parts and use the cache to speed it up
    policy: pull-push
    paths:
      - vendor/
  # we use this artifact for all the jobs
  artifacts:
    name: "vendor"
    paths:
      - vendor/*
    expire_in: 2 hour

validate:
  stage: check
  script:
    - composer validate
    - vendor/bin/phpcs --basepath=. --report-json=php_codesniffer.json
  artifacts:
    paths:
      - php_codesniffer.json
    when: always
  needs:
    - prepare_cache
  dependencies:
    - prepare_cache

phpmd:
  stage: check
  script:
    - vendor/bin/phpmd src/ text phpmd.xml.dist
  needs:
    - prepare_cache
  dependencies:
    - prepare_cache

psalm:
  stage: check
  script:
    # check for psalm errors
    - vendor/bin/psalm --report=psalm.json
  artifacts:
    paths:
      - psalm.json
    when: always
  needs:
    - prepare_cache
  dependencies:
    - prepare_cache

# PHP 8.0
test_lowest:
  parallel:
    matrix:
      - PHP: [ 80, 81, 82]
  image: registry.gitlab.com/tjvb/phpimages:php$PHP
  stage: test
  script:
    - composer update --prefer-lowest
    - vendor/bin/phpunit --coverage-text --colors=never --coverage-cobertura=phpunitresult/cobertura-coverage.xml --log-junit=phpunitresult/junit.xml
    - sed -i 's~ filename="~ filename="src/~' phpunitresult/cobertura-coverage.xml
  coverage: '/^\s*Lines:\s*\d+.\d+\%/'
  artifacts:
    reports:
      junit: phpunitresult/junit.xml
      coverage_report:
        coverage_format: cobertura
        path: phpunitresult/cobertura-coverage.xml
  needs:
    - prepare_cache
  dependencies:
    - prepare_cache

test:
  parallel:
    matrix:
      - LARAVEL: 9
        TESTBENCH: 7
        PHP:
          - 80
          - 81
          - 82
      - LARAVEL: 10
        TESTBENCH: 8
        PHP:
          - 81
          - 82
  image: registry.gitlab.com/tjvb/phpimages:php$PHP
  stage: test
  script:
    - echo "Laravel $LARAVEL"
    - composer require --dev "orchestra/testbench=^$TESTBENCH"
    - vendor/bin/phpunit --coverage-text --colors=never --coverage-cobertura=phpunitresult/cobertura-coverage.xml --log-junit=phpunitresult/junit.xml
    - sed -i 's~ filename="~ filename="src/~' phpunitresult/cobertura-coverage.xml
  coverage: '/^\s*Lines:\s*\d+.\d+\%/'
  artifacts:
    reports:
      junit: phpunitresult/junit.xml
      coverage_report:
        coverage_format: cobertura
        path: phpunitresult/cobertura-coverage.xml
  needs:
    - prepare_cache
  dependencies:
    - prepare_cache
